{% set version = "0.10.0" %}

package:
  name: mwclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mwclient/mwclient-{{ version }}.tar.gz
  sha256: c3f1598a5f75fb80e9b8373f6574042208358aed81470fc2178a8ae7474069af
  
build:
  number: 1003
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests-oauthlib
    - six

test:
  imports:
    - mwclient

about:
  home: https://github.com/mwclient/mwclient
  license: MIT
  summary: 'MediaWiki API client'
  license_family: MIT
  license_file: LICENSE.md
  doc_url: http://mwclient.readthedocs.io/en/latest/user/index.html
  dev_url: https://github.com/mwclient/mwclient

extra:
  recipe-maintainers:
    - JohnGreeley
