{% set name = "mwclient" %}
{% set version = "0.9.1" %}
{% set sha256 = "ed7a0eeb98f0309946ae8762b60eae10eb507e4b67400931ec24abd0aee3d7b4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests-oauthlib
    - six

test:
  imports:
    - mwclient

about:
  home: https://github.com/mwclient/mwclient
  license: MIT
  summary: 'MediaWiki API client'
  license_family: MIT
  license_file: LICENSE.md
  doc_url: http://mwclient.readthedocs.io/en/latest/user/index.html
  dev_url: https://github.com/mwclient/mwclient

extra:
  recipe-maintainers:
    - JohnGreeley
