{% set name = "mwclient" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mwclient-{{ version }}.tar.gz
  sha256: 79363dd8d12f5e3b91b92b63152bf9dfef27da786c076a244e1f148c8dd67139

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests-oauthlib
    - six

test:
  imports:
    - mwclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mwclient/mwclient
  summary: MediaWiki API client
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://mwclient.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anthchirp
