{% set version = "0.10.1" %}

package:
  name: mwclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mwclient/mwclient-{{ version }}.tar.gz
  sha256: 79363dd8d12f5e3b91b92b63152bf9dfef27da786c076a244e1f148c8dd67139

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests-oauthlib
    - six

test:
  imports:
    - mwclient

about:
  home: https://github.com/mwclient/mwclient
  license: MIT
  summary: MediaWiki API client
  license_family: MIT
  license_file: LICENSE.md
  doc_url: http://mwclient.readthedocs.io/en/latest/user/index.html
  dev_url: https://github.com/mwclient/mwclient

extra:
  recipe-maintainers:
    - JohnGreeley
